### ISSUE TITLE
Promotion selector is not shown.

### ISSUE THREAD

**Issue by edwardocano** [lichess-org/flutter-chessground#33]
When the movement of the chessboard is using playunchecked() and a pawn arrived to the other side the promotion selector is now shown and the pawn stays stuck there forever.

**Comment by veloce** [comment]
Sorry but I don't understand the issue. `playUnchecked()` isn't part of chessground which doesn't has chess logic.

**Comment by edwardocano** [comment]
Hello! i am using dartchess and chessground, when i make a movement in the board just sending the coordinate and not by a hand gesture the promotion selector is not shown. I was checking the code and it only can be activated whith a hand gesture.

**Comment by veloce** [comment]
Programmatically opening the promotion selector was never intended. So I'm closing this.
