### ISSUE TITLE
Tapping still doesn’t cancel premoves

### ISSUE THREAD

**Issue by sorsted** [lichess-org/flutter-chessground#42]
[This issue](https://github.com/lichess-org/flutter-chessground/issues/22#issue-1812444620) is still there for me. I am using a clone of the main branch from a couple of days ago.

**Comment by veloce** [comment]
I don't reproduce. And widget tests say the contrary: https://github.com/lichess-org/flutter-chessground/blob/b789031bf15c20576879ff366c51ca4bb8f5d32b/test/widgets/board_test.dart#L559

**Comment by veloce** [comment]
I maintain the feature works as intended in this package.

**Comment by sorsted** [comment]
Is this convincing enough? 

I'm using a clone from today.

https://github.com/user-attachments/assets/6c81dfaa-e4c9-49aa-ad93-a7248e6dd550

**Comment by veloce** [comment]
Finally understood what you meant. The piece is not deselected if tapped again. Ok, will fix.

**Comment by veloce** [comment]
I remember I changed the behaviour after that issue: https://github.com/lichess-org/mobile/issues/740

So I don't understand anymore.

**Comment by sorsted** [comment]
> Finally understood what you meant. The piece is not deselected if tapped again.

It's not just that. As you see, I simply cannot cancel a premove, except by making another premove.

**Comment by veloce** [comment]
No, you can. By tapping anywhere on the board expect your own pieces.

I found the difference with lichess website: the [how do you move pieces settings](https://lichess.org/account/preferences/game-behavior#howDoYouMovePieces) makes it behave differently if you choose "click" only or drag.

**Comment by sorsted** [comment]
@veloce Great.

Anyway, if tapping anywhere also cancels premoves, then [this other issue of mine](https://github.com/lichess-org/flutter-chessground/issues/41) becomes related. I maintain that if you make both sides interactable and turn premoves on, then the expected behaviour is that premoves should be allowed on both sides. But then clearly it doesn’t work that premoves can be cancelled by tapping anywhere. This would lead to conflicts with the opponent’s ability to make moves by tapping on two squares (and their ability to cancel the selection of a particular piece by tapping elsewhere).

The expected behaviour in this case would be (I think):

* If you made a premove, then tapping any of your own pieces should cancel that premove.
* If you tapped a piece to (pre)move it, then tapping any of your own pieces should cancel that (pre)move, unless that piece was a valid (pre)move destination. As we all know, your own pieces might very well be a valid premove destination if your opponent captures that piece in the next round. It can also be a valid move destination since moving your king onto your rook means castling.
